pub const DATA_TO_USE: &[(&str, &str)] = &[
	("Accessibility","GetOleaccVersionInfo"),
	("Accessibility","GetRoleTextA"),
	("Accessibility","GetRoleTextW"),
	("Accessibility","GetStateTextA"),
	("Accessibility","GetStateTextW"),
	("Accessibility","IsWinEventHookInstalled"),
	("Accessibility","NotifyWinEvent"),
	("Accessibility","SetWinEventHook"),
	("Accessibility","UiaClientsAreListening"),
	("Accessibility","UiaRegisterProviderCallback"),
	("Accessibility","UnhookWinEvent"),
	("Antimalware","AmsiUninitialize"),
	("AppLocker","SaferCloseLevel"),
];
